name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    environment: development
    env:
      CI: "1"
      TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tuist
        run: make install

      - name: Run Tests
        run: make test

