name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Tuist state and SelectiveTests
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/tuist
            ~/.cache/tuist/SelectiveTests
            ~/Library/Caches/tuist
            ~/Library/Caches/tuist/SelectiveTests
          key: ${{ runner.os }}-tuist
          restore-keys: |
            ${{ runner.os }}-tuist

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-deriveddata

      - name: Install Tuist
        run: make install

      - name: Run Tests
        run: make test
