name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    environment: development
    env:
      CI: "1"
      TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install Tuist
        run: make install

      - name: Run Tests
        shell: bash
        run: |
          eval "$($HOME/.local/bin/mise activate bash)"
          make test
